### PR TITLE
Add dependencies

### PR DESCRIPTION
**Pull request by peculiarity**
This reverts commit 9949e39795fe03df42021928aed4253359715495.
Add `IAuth.sol`, `Auth.sol` and `MathLib.sol`

### CODE REVIEW

**Comment by lemunozm** [comment]
Can we add in this PR at least `MathLib.sol`, `IAuth.sol` and `Auth.sol`?

Those are all the base for the rest of PRs

**Comment by wischli** [comment]
For `MathLib.sol`, you could cherry-pick [e55352d](https://github.com/centrifuge/asset-pools/pull/9/commits/e55352d477f2bbc3d4c4c7251d9660e86772c86b) but I suppose doing it yourself is faster.

**Review by lemunozm — APPROVED** [review]
Approved in case you go splitting the PR

**Comment by peculiarity** [comment]
@lemunozm  @wischli  You can check it out once again. :)

**Review by wischli — APPROVED** [review]
Thanks!

**Pull request merged**
