### PR TITLE
Makes CI to fail if warning

### PR DESCRIPTION
**Pull request by lemunozm**
Feel free to disagree with. 

I think we should force the CI to warn us about warnings.

### CODE REVIEW

**Review by hieronx — APPROVED** [review]
Maybe there are some warnings we might want to intentionally ignore, but for now, I agree this is worth adding. Can always remove it again later.

**Comment by lemunozm** [comment]
Does there exist some kind of "warning lint" section, for that matter? In Rust you can enable/disable a subset of warnings

**Comment by lemunozm** [comment]
I've changed it to be a `foundry.toml` property instead

**Comment by hieronx** [comment]
> Does there exist some kind of "warning lint" section, for that matter? In Rust you can enable/disable a subset of warnings

https://book.getfoundry.sh/reference/config/solidity-compiler#ignored_error_codes

**Review by hieronx — APPROVED** [review]

**Review by peculiarity — APPROVED** [review]

**Pull request merged**
